### ISSUE TITLE
THub Research: Symfony 4 Security

### ISSUE THREAD

**Issue by mikemilano** [thinktandem/tandem#101]
Objective here is to go through all the latest S4 security with the goal of coming up with the best authentication solution for THub & API Platform.

Oauth2 comes to mind but more research needs to be done. If the effort is too big, other authentication methods would be acceptable and we can revisit at a later date.

The alternative is less formal token based authentication which doesn't involve features like `scope` and refresh tokens.

**Comment by mikemilano** [comment]
As of this morning I wrapped up the Security course. https://symfonycasts.com/certificates/E7298E96C106

Next up is a deep dive into API platform for the latest and greatest as fresh courses are being released one by one, over the course of the next couple weeks.

Will be able to make an informed decision and start churning out the auth architecture immediately after this last round of symfony based research.

**Comment by pirog** [comment]
@mikemilano awesome! thanks for spinning up an issue here for tracking purposes
