### ISSUE TITLE
[lando-tandem] We need an easy way to install the lando-tandem plugin.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#103]
## What is to be done?

We need an easy way to install the `lando-tandem` plugin.

For example `hyperdrive` can be installed by a user by issuing a single curl command that you can copy and paste from the project README.md file.  That is accomplished by a release script that generates a binary that the curl command can reference to kick off the install for the user.

In this card we should research if we can just point directly at the `get-plugin.sh` file on GitHub or if we need to implement the release binary like in hyperdrive.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

* https://github.com/thinktandem/tandem/issues/98 Auto updating mechanism

**Comment by serundeputy** [comment]
I've updated the `README.md` file w/ instructions to install the `lando-tandem` plugin from the internet sans token: https://github.com/thinktandem/lando-tandem

```bash
curl -H 'Accept: application/vnd.github.v3.raw' -o /tmp/get-plugin.sh https://api.github.com/repos/thinktandem/lando-tandem/contents/scripts/get-plugin.sh && \
chmod +x /tmp/get-plugin.sh && \
/tmp/get-plugin.sh && \
yarn --cwd ~/.lando/plugins/lando-tandem
```

**Comment by pirog** [comment]
@serundeputy nice, definitely a big improvement here. 

I am wondering how we should handle the node deps though? It seems to me like the script itself should have another function to handle installing the deps, so we dont have to rely on a manual step from the user to do that?

I think we can do something like 
`yarn install | npm install | echo "need to install either yarn or npm"` 
eg try yarn install first and then npm and then print an error

How do you feel about getting something like that in there before we close this out?

**Comment by serundeputy** [comment]
Yeah let's keep this open and I'll give it a go this coming week!

**Comment by pirog** [comment]
Awesome! sounds good

**Comment by pirog** [comment]
@serundeputy when we've got the install one-liner down we need to add installation of this plugin to https://docs.thinktandem.io/handbook/onboarding.html#_4-get-the-tools-you-need

im guessing adding it after Lando makes sense and having it include 

1. the one-liner to install it
2. a brief description of the plugin and what it does/why it exists
3. a link to the github repo for further readings

i dont think this needs to be a separate tandem board card, maybe just up the points here a bit instead

**Comment by pirog** [comment]
@serundeputy it might also be worth creating a stubbed ticket  
to create a `lando plugin install` command that can live directly in lando so that eventually our install step is `lando install plugin lando-tandem` instead of our BASH FROM THE INTERNET one liner.

No idea on the timeline for actually doing that but def is something we need to do eventually!

**Comment by serundeputy** [comment]
> yarn install | npm install | echo "need to install either yarn or npm"

* I've added the `yarn|npm|warning` fallback as part of the [`get-plugin.sh`](https://github.com/thinktandem/lando-tandem/blob/master/scripts/get-plugin.sh#L57) script.
* I've updated the one-liner install from the internet line in the [readme](https://github.com/thinktandem/lando-tandem/blob/master/README.md)

>im guessing adding it after Lando makes sense and having it include
the one-liner to install it
a brief description of the plugin and what it does/why it exists
a link to the github repo for further readings

* Added some docs to `Onboarding` section of Tandem docs about `lando-tandem` plugin.
  - PR: https://github.com/thinktandem/tandem/pull/119
