### ISSUE TITLE
platform.sh automatic backups are not working on many sites

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#109]
## What is to be done?

Many of our platform.sh projects, start states, etc contain cron tasks to take nightly snapshots. 
see: https://github.com/thinktandem/tandem/blob/master/.platform.app.yaml#L40 as an example

However, these do not run unless you also set `PLATFORMSH_CLI_TOKEN` on the master environment
see: https://docs.platform.sh/development/cli/api-tokens.html#install-the-cli-on-a-platformsh-environment

**It does not seem that we are doing this on most of our projects.** This is easy to investigate and verify. Obviously we want to be taking backups in case databases get fucked.

```bash
lando platform ssh

# from platform 
cat /tmp/log/cron.log

[2019-09-05 03:02:38.781678] Launching command 'if [ "$PLATFORM_BRANCH" = master ]; then
  /app/.platformsh/bin/platform snapshot:create --yes --no-wait
fi
'.

  [LoginRequiredException]
  Authentication is required.

  Please log in by running:
      platform login

  To authenticate non-interactively using an API token, see:
      https://docs.platform.sh/gettingstarted/cli/api-tokens.html</comment>
```

We need to make sure that we are and we also need to make sure that we add this as a _required_ step in our project spin up docs currently being worked on over at #78 

The following one liner is a really easy way to win this
```bash
platform variable:create -e master --level environment --name env:PLATFORMSH_CLI_TOKEN --sensitive true --value 'your API token'
```

Action items

1. Go through all our platform.sh sites and make sure `PLATFORMSH_CLI_TOKEN` is set in the master environment of each
2. Add this as a required step in #78 
3. Make sure all our start states ship with automatic backups configured in their platform.yamlz

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

1. Finish up #78 so we can get this documented so it stops happening

**Comment by labboy0276** [comment]
@mikemilano can you add your thoughts on this card that you were discussing in the engineering channel yesterday please.

**Comment by pirog** [comment]
@labboy0276 see this https://thinktandem.slack.com/archives/CE2KZ58DV/p1567696991016500

**Comment by mikemilano** [comment]
@labboy0276 I think they may be out of scope of this ticket, but I was commenting that we could add a health check which looks across all projects to make sure backups are being made.

This might look like a CLI app which is run daily that uses the [p.sh PHP Client](https://github.com/platformsh/platformsh-client-php) to fetch the production environment of each project and make sure a backup exists from within the last day. Notifications would be sent to Slack to assure the check was being run, and include project info for any that are missing backups within the given threshold.

To be clear, it would be one script that is responsible for checking all projects, as opposed to each project checking itself. 

I think this should be its own effort though as either a Symfony console app, or even a vanilla PHP script. I would put this on an "ops" server, but if we don't like the idea of maintaining it, it could be put in the codebase of our main platform app.
