### ISSUE TITLE
Do more Lando outreach while people are stuck at home

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#132]
@serundeputy we should try to meet up with AJH as part of this sometime in the next few weeks to start coordinating Lando outreach efforts. People are at home nervous and bored so we should accelerate engagement. Here are some ideas of things we could do

- [x] Find some "good for first issue" issues, prep them a bit and then email people who might help
- [x] Doing a monthly Lando webinar for sponsors who are stuck at home #148 
- [ ] Start our first contributors sprint planning meeting
- [ ] Launch the blogger program earlier, tweet? @serundeputy 
- [ ] Launch the guider program earlier, tweet? @serundeputy

**Comment by pirog** [comment]
A good "shovel ready" idea that would combine many of the above is to include guides/blogs in the "good first issue" solicitation. @serundeputy

**Comment by pirog** [comment]
```<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <body>
    <p>Hey *|FNAME|*,</p>
    <p>One of our greatest failings to date has been the lack of a solid and well organized contributor program. We aim to change that very soon but we aren't quite ready yet. That said, please stick around!</p>
    <p>After we launch the stable Lando release on May 4th we plan to hold weekly contributor meetings so we can focus our effort on the right things and make sure PR's are getting merged.</p>
    <p>Please bear with us and you will hear from us right after we launch stable Lando!</p>
    <p>Mike Pirog</p>
    <small>If you don't wish to receive further messages from Lando then <a href="*|UNSUB|*">let us know.</a>
  </small>
</body>
</html>```

**Comment by serundeputy** [comment]
@pirog sent out a test email yesterday to you and i

```html
<html>
  <body>
    <p>Hey *|FNAME|*,</p>
    <p>
      Stuck at home? Looking for ways to stay mentally active?
    </p>
    <p>
      This is a great time to help out the Lando Alliacnce with PRs. We've tagged a list of issues just for this purpose.
      <ul><li><a href="https://github.com/lando/lando/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22">Good First Issue</a></li></ul>
    </p>
    <p>
      If you need help getting started or getting your issue over the finish line join us in the 
      <a href="https://launchpass.com/devwithlando">#contributors</a> channel on Lando slack.
    </p>
    <p>
      ~Geoff St. Pierre
    </p>
    <small>
      If you don't wish to receive further messages from Lando then <a href="*|UNSUB|*">let us know.</a>
    </small>
  </body>
</html>
```

**Comment by serundeputy** [comment]
Schedule some tweets about Blogger and Guider programs.

Hit the slack channels too.

**Comment by serundeputy** [comment]
I've sent a prompt to the `contributors` lando slack channel.
https://devwithlando.slack.com/archives/C91MQ5084/p1586176267031800

**Comment by pirog** [comment]
Nice! i saw that @serundeputy. We can chat more about this tomorrow but i think we should take @dustinleblanc's suggestion and pivot our strategy to be pinging people directly in slack and on twitter.

**Comment by serundeputy** [comment]
Be active/more active in slack.

Monitor for good guides
  - write the issue  
  - solicit for guide writers


- [ ] Ping #community channel with awareness of the #contributor channel

- [ ] Ping #contributor channel
  - anyone have a good guide/.lando.yml file
  - anyone have a good case study/blog post
