### ISSUE TITLE
Migration Webinar

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#146]
Reach out to the Lando network to promote a Drupal 8 migration webinar.

**Marketing**
- [x] Email for signup, including migration blog articles.
- [x] Webinar signup. 
- [x] Make sure we have webinar setup for recording/participation (Google Meet free Enterprise)
- [ ] Second notification.
- [ ] Automated campaign for people who engage but don't signup.

**Content**
Dustin + John collaborate?

- [x] Pre/post-webinar supplemental material
- [x] Presentation
- [x] Migration Webinar I blog post on thinktandem.io
  * include youtube video that @dustinleblanc will upload to the Lando youtube channel
  * include copy and pasta commands from the webinar

**Post Webinar**
- [x] ~~Email thanking people with link to recording and supplemental material. "Need help with your migration?" contact.~~
  * We've decided to have the follow up email to follow Migration II Webinar https://github.com/thinktandem/tandem/issues/156

**Comment by pirog** [comment]
Some other things to consider

* Can we include any D9 language in the marketing/content for this? 
* Do we want to allow chat for questions during the preso or something, maybe @dustinleblanc can moderate?
* We probably want to include a bunch of materials to go along with this eg blog posts etc

**Comment by dustinleblanc** [comment]
Follow up:

> Make sure we have webinar setup for recording/participation (Google Meet free Enterprise)

Have we tested that out? A lot of the Q& A session stuff I've been seeing lately has been what looked like Zoom meetings being multicast via periscope/youtube/etc/

https://restream.io/ is a good tool for streaming the same content to multiple platforms and being able to collect chat/questions from those different platforms to address during the stream. The content is then saved on Youtube/periscope, etc

**Comment by dustinleblanc** [comment]
https://www.youtube.com/watch?v=CFzvA1dEvd8 is an example of what I'm talking about

**Comment by pirog** [comment]
@dustinleblanc good suggestion from @serundeputy that as you are MCing/moderating to identify any participants that are "hot to trot" for Tandem related services eg might be amenable to a direct sale after the webinar is done.

**Comment by serundeputy** [comment]
@labboy0276 you can use this ticket for writing the follow up blog post to Migration I Webinar.

**Comment by labboy0276** [comment]
https://thinktandem.io/blog/2020/04/28/lando-migration-webinar-part-1-followup/
