### ISSUE TITLE
Start monthly Lando webinar for sponsors

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#148]
So things to consider here

- [ ] Should we make this free for nowish?
- [ ] Do we want to solicit current sponsors and let them guide the content of the first few webinars?

@serundeputy @reynoldsalec ^ thoughts?

**Comment by serundeputy** [comment]
> Should we make this free for nowish?

  * I think the first one on Migrations should be free and we see if we have the good problem of too many people and then we go from there.

> Do we want to solicit current sponsors and let them guide the content of the first few webinars?

  * I would like to solicit the sponsors and see what kind of content they are interested in and see if we can provide it and/or invite guest speakers if they have it
