### ISSUE TITLE
How do we get everyone involved in sales who wants to be?

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#18]
**What Should We Talk About?**

Virtually all members of our team have expressed interest in getting deeper involved in our sales process in different capacities. Let's talk about...

- Types of Sales Roles and Activities. Examples include...
  - Lead generation
  - Initial client calls
  - Client qualification
  - Client follow-up and "massaging" clients down the funnel.
  - Content marketing (creating content, directing it to passive leads)
  - Writing project briefs
  - Estimation
  - Writing proposals
- Who in our immediate team is interested in different areas?
- Ideal participation in sales (how much time? what areas would allow for the most productive cross-collaboration?)
- What would be a good way to expose new team members to sales?

**Checklist**

- [x] I've selected the label that _best_ describes what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**

**Comment by pirog** [comment]
@reynoldsalec i'm going to keep this open as a "task" but suggest you break it up into task(s) and discussion(s) as you see fit.

**Comment by pirog** [comment]
@reynoldsalec whats the status of this? I dont see any obvious actionable task. Should we close, icebox for later, etc?
