### ISSUE TITLE
Establish and define our modified Gitflow process

### ISSUE THREAD

**Issue by mikemilano** [thinktandem/tandem#2]
> Note: *Github workflow* (aka Githubflow) and *Git workflow* (aka Gitflow) are different. *Github flow* is a vague derivative of *Gitflow*.

Objectives:
1. Discuss and adopt a more detailed Gitflow operating procedure
2. Document it in the 2.0 docs

Currently we define a [Github Workflow](https://guides.github.com/introduction/flow/) in the  process docs and lightly elaborate, but it would be helpful if we defined the Git workflow in detail as it applies to Tandem.

Why? Because the [Github Workflow](https://guides.github.com/introduction/flow/) doc is light on the concept it encapsulates, which is a Git workflow design "made popular by [Vincent Driessen at nvie](https://nvie.com/posts/a-successful-git-branching-model/)". (Source, [Atlassian](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow))

The common theme among most Gitflow examples is that the `master` branch is always the deployable branch, and the `develop` branch is typically where the latest integrations are merged into.

Strategy and naming conventions beyond this may change slightly by its practitioners based on a variety of project factors.

Note: Our workflow (in the old docs) is inconsistent with a Gitflow in that is there is no `develop` branch, and our docs instruct the developer to branch features directly off `master`. 

The concept of an integration branch (`develop`) is important to maintain changes towards a release while hotfixes can still be released to `master` without deploying any other work that is not ready to be released.

> Note: Different projects may merit different branching strategies. The one I'm referring to here is for agency website development work. Product development may or may not warrant different strategies based on how releases and collaboration happens.

I've seen us use a branch named `test` as a sort of integration branch, but it is still inconsistent with our existing docs which have us branch from `master`.

We should be using `develop` instead of `test` as it is an unofficial standard of sorts as seen in the references above. I'd also argue the name `test` has its own meaning and should not be used for a branch name unless it was a branch created to maintain an environment for automated tests.

Minimally, the following should be defined in this document.

- Branch naming (`master`, `develop`)
- Feature branches strategy (including naming conventions and acceptance process)
- Hotfix strategy
- Release strategy (i.e. tagging or branch names if applicable; This may even vary based on project params)
- Hosting provider specifics; For example, we may release differently on Platform than we do Pantheon based on Github integration constraints.

**Comment by pirog** [comment]
@mikemilano im going to close this out just to clean house a bit. 

i updated [this guide](https://docs.thinktandem.io/guides/contributing-code.html) a bit when i moved it from our old docs and after you spun up this ticket. i _think_ it addresses some, but not all, of the concerns you have here so it might be good to surface what ive missed. if you are motivated i would spin relevant tasks/discussions for those thing

**Comment by pirog** [comment]
@mikemilano  fake out!

backtracking here. after looking at a few of the other issues i think it makes more sense from a tracking perspective to keep this open and classify it as a "note"

**Comment by mikemilano** [comment]
Re-created as #72
