### ISSUE TITLE
How should we distribute activity/changes in this issue queue and/or changes in its docs?

### ISSUE THREAD

**Issue by dustinleblanc** [thinktandem/tandem#38]
We probably want a way to ping people about new discussions, or changes to things like our company employee handbook, manifesto etc. Slack seems like the easiest and fastest way to start doing that. 

What do we all think?

**Comment by dustinleblanc** [comment]
I've requested the slack/Github integration to the `thinktandem` org owner

**Comment by pirog** [comment]
@dustinleblanc i'm not clear on what the goal/purpose of this task is. What are we trying to accomplish here? If we aren't pretty sure about the goals etc it might be worth converting to a discussion.

**Comment by dustinleblanc** [comment]
We're trying to accomplish everyone being notified of new issues on the repo so that they don't miss new discussions, perhaps there is a better way to do that.

**Comment by pirog** [comment]
@dustinleblanc seems worth a discussion to me. 

if you disagree i think at the very least we want to work on this card so its purpose is clear and someone else could execute it and understand what they are trying to do.

**Comment by dustinleblanc** [comment]
Yeah lets convert it, I was jumping right to some ACTION

![image](https://user-images.githubusercontent.com/3948808/60594964-15dbbc00-9d74-11e9-8091-dd4f6756f5a8.png)

**Comment by pirog** [comment]
I dig that you are a MAN OF ACTION since i fancy myself a man with similar inclinations. that said, one of the primary reasons for this whole company building system and setup is to SLOW THINGS DOWN, force deliberation/collaboration, get buy in and feedback from others, etc, that way when we do ACT we know its, in the words of Thomas Jefferson on almost this day many years ago

> the most wholesome and necessary for the public good.

**Comment by pirog** [comment]
So having a separate "discussions" and/or "new issues" channel(s) in slack makes sense to me for those two things. Having more "important" updates like changes to the manifesto/handbook show up someplace like #general makes sense to me. It also might be worth surfacing new guides there as well so we have another way to disseminate updates and helpful materials besides our friday meetings, etc.

**Comment by dustinleblanc** [comment]
@pirog yep, that makes sense to me too. I think the default Github > Slack integration is going to lack the ability for us to fine tune this the more I think about it. We might need a custom webhook receive that can route based on that kind of logic

**Comment by pirog** [comment]
Just to follow up here. I've got a task to split this up into two actionable tasks:

1. rules for what shit should go where and how
2. the tech to make the above happen

It's in my backlog because we've got bigger fish to fry for now!

**Comment by pirog** [comment]
I'm guessing we should put this on the back burner a bit until we get other things eg Tandem Hub/Plugin rolling a bit further
