### ISSUE TITLE
Add benefit for MyersBriggs and/or CliftonStrengths finder reports

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#50]
## Prompt

Over the last few months we've discussed casually how it would be cool for some sort of opt-in (read: voluntary) benefit where employees could take either/both the Clifton StrengthFinder or MyersBriggs tests. 

I think this would be a great way for individuals to get a better understanding of their strengths. By extension it would also be a great way for other team members to get better insights on what makes us tick. This seems like a natural extension of our desire to do professional development and build a cohesive team that works well together. Over time it might even help aligning roles/responsibilities and tasks to certain people as obvious trends start emerging. 

## Ticket Checklist

Make sure you complete the following checklist

- [x] I'm aware of [what a discussion actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've assigned this task to myself and one of the Keepers of the Faith
- [x] I've **not** set a story point estimation
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc

## Ping some folks!

Discussions only work when people _actually discuss_. To aid that process it's worth pinging the people who you think might be most interested in contributing to the discussion. Do that here!

@dustinleblanc @mikemilano you guys are the ones ive spoken to the most about this but it would be great to hear from everybody on this. 

## Follow up tasks

No follow up tasks yet.

**Comment by reynoldsalec** [comment]
These should fall within our existing continuing education stipend.

**Comment by pirog** [comment]
@reynoldsalec the thinking here is to incentivize people to do this, eg make it an explicit (although still voluntary) part of onboarding and listed as a benefit. I think we want to do this because its valuable data for both Tandem and the person themselves. 

if we draw from some other stipend then people are going to need to make a tradeoff between doing this or something else and that obviously lowers the incentive. We are only talking about probably less than $100 a person here.

**Comment by mikemilano** [comment]
My thoughts:

## Privacy:
On a personal note, I was horrified at the thought of a psych test when Dustin suggested it. The Clifton site was interesting though, so I took it out of my own curiosity. Once I went through the result, it was clear the focus was on professional related strengths, and I was OK with sharing it.

Despite how professionally focused any test like this is, and despite we're recognizing this as an opt-in from the beginning, we should emphasize 1) it's first and foremost for personal curiosity/self improvement, and 2) there's absolutely no expectation to share the results.

## Accuracy:
I'm suspect I could have ended up with different results depending on my mood at the time I took the Clifton Strengths assessment. I also missed a few questions based on the ambiguity of the questions. That said, I think there was value in the results.

## Tandem's Usage of the Data
It makes sense that we might be able to use the data, but are we really going to? If so, we would need to dedicate time to figuring out how to interpret Clifton results and how they would map to preferential assignments with Tandem.
