### ISSUE TITLE
Flesh out "Interview Process" doc.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#69]
## What is to be done?

In our v1 Tandem docs the `Interview Process` doc never made it past a stub: https://docs.v1.thinktandem.io/hiring/interviews.html.

We need to write and add a PR for `Interview Process` against our v2 thinktandem/tandem docs repo.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

**Comment by reynoldsalec** [comment]
A few existing Google Drive docs we've used that may be helpful for completing this card:

- [Old Interview Question List](https://docs.google.com/document/d/1YDa5rJslyR1efezqQ4jl2YaIGfADLN0SIMGjI7aVe9E/edit): This list has some good general questions for a non-technical interview. A subset of these might be good for an initial phone screen.
- [Laravel Dev Position Question List](https://docs.google.com/document/d/1yE53RjZXVPBIfePJ8v9WgFbtFEINFk-9H3_ZK4zLbtw/edit) A few more specific questions for a backend focused position.
- [Junior Dev Position Question List](https://docs.google.com/document/d/1n1OZeQMLcPrTrqxoP17yKGcLkJPo5i2ibwlgZYgoOp0/edit) Some more general technical questions.

PM Question List

- What PM software are you familiar with?
