### ISSUE TITLE
Standardize time based documentation and discussions on a specific timezone

### ISSUE THREAD

**Issue by mikemilano** [thinktandem/tandem#73]
I'm proposing we standardize on a specific timezone for communication. 

Currently when throwing dates around, we need to either include a timezone or make an assumption based on who it's coming from.

Even if we are using timezones in documentation, which one should we standardize on?

If we were to standardize on Eastern time for example, it would be understood that times are EST unless another timezone was specified.

Do we use Pacific since we're more officially based on the west coast? or do we use Eastern since the majority is over there now? Basing it off the location of the majority might cause problems later if the majority changes.

## Ticket Checklist

Make sure you complete the following checklist

- [ x] I'm aware of [what a discussion actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x ] I've assigned this task to myself and one of the Keepers of the Faith
- [x ] I've **not** set a story point estimation
- [x ] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc

## Ping some folks!

Discussions only work when people _actually discuss_. To aid that process it's worth pinging the people who you think might be most interested in contributing to the discussion. Do that here!

> Example: Hey @pirog @reynoldsalec @dustinleblanc ! Tell me what you think!

**Comment by reynoldsalec** [comment]
Just a note that the current requirements we communicate are availability for meetings as early as 8AM PST/11AM EST. From there I've always operated on the knowledge of our other team member's timezones. For example, I try to schedule meetings for EST folks before 5 or 6PM their time.

As a rule I always communicate with our clients/team members using their timezone (AKA if I send something to Dustin, I'll say 2PM EST, but if I send something to Josh, I'll say 11AM PST). Slack definitely makes this easy for our team members, for clients I suppose we should specify it on the project brief.

**Comment by dustinleblanc** [comment]
We definitely have clients in odd timezones too. I try to do something similar to Alec, but at times I find myself just using EST and trying to call out that it is EST. 

If we were to standardize time, it would seem to me that forcing **everyone** to calculate based on UTC/GMT would make sense. This is impartial and matches with the conventions used in our software.

I don't personally think standardization is required, but I would go as far as saying that specification of timezone when talking about times would be a really good idea. It's the easiest habit to implement, even if it does still push work onto other people to translate the times you specify.

Alec mentioned Slack helping indicate local time for team members, and I know there are some tools designed to show what time it is for your teams (we used one at Pantheon), but does anyone else know of a really quck to use tool to convert timezones for Mac/Linux? I often literally Google something like "2PM EST in X Timezone" and it works pretty well, but having that be even quicker to execute would make it very quick to translate for the receiver.

**Comment by mikemilano** [comment]
I got pretty used to using EST when working for the last company. That said, I also used to fly planes and never got used to calculating the 7 or 8 hour difference for UTC. That's tough. :D 

I think most companies use the place they are based.

It's more a call to define how to operate, even if that is to standardize on figuring out whatever makes sense to the individual person at the moment.

It would be good to define a timezone for consistent documentation, like our operating docs that state regular meeting times and such.  I think it makes most sense for that to be Pacific or Eastern.

**Comment by pirog** [comment]
So im here to mostly triage this issue and get it turned into an actionable task which is why im just going to propose what makes the most sense to me based on feedback and personal thoughts.

> Totally cool with having a standardized time zone. I dig the theoretic usage and neutrality of UTC but i think that might be pretty hard in practice. EST makes sense because most of our people are here but thats not necessarily going to stay the same. PST makes sense because we are actually "based" there, as much as a remote company can be based somewhere. 

The bigger questions i have here are

1. How do we actually enforce something like this? We can throw it up in the docs and tell people to express all times in PS(D)T but is it realistic for people to just consistently do that and if it isnt dont we run a potentially bigger risk of a timezone mismatch if person A _assumes_ person B means PST because its the "rule" but they have just used their own timezone of EST because its a pretty hard habit to break?
2. Is this an actual problem we are having or is a problem we are going to have _soonish?_ Eg have we missed important meetings, lost sales, or been materially or deeply spiritually damaged by this?

Honestly do not know the answer to the two above questions but wanted to help provide some thoughtful questions to help navigate this discussion.

**Comment by reynoldsalec** [comment]
Personally I don't find this to be an issue; the golden rule seems to be to always specify the timezone you're referring to. The actionable task I could see if creating a page in the Handbook about working remotely; that would be a good place for us to acknowledge this timezone issue and talk about how we handle other remote working issues (background noise on calls, internet quality, communication siloing, etc.)

**Comment by pirog** [comment]
I'd support that. it would be good to have a section that talks more explicitly about our remote work environment anyway.

**Comment by pirog** [comment]
Alright see: https://github.com/thinktandem/tandem/issues/113 as the follow up task for this
