### ISSUE TITLE
Create a guide for spinning up a new project

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#78]
## What is to be done?

We want to take some of the work over at #54 and our usual https://thinktandem.io/blog/2017/10/23/killer-d8-workflow-using-lando-and-platform-sh/ devops set up and create a guide about how we spin up new projects. It should _at least_ contain the follow steps

1. Choosing a start state from our list of start states
2. Creating a new repo and forking the start state to the repo
3. Adding it to the spreadsheet of current projects (note that we want to make sure this is not public)
4. Making sure lando is configured correctly (usually just a trivial name change etc)
5. Setting up platform.sh and github integration
6. Setting up additional devops things eg travis, etc
7. @labboy0276 any other steps we usually do that i've missed

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Ping @serundeputy over at #76 or one of #76's follow up tasks so he knows this guide exists as it will likely serve as an "MVP" for his stuff. 

* https://github.com/thinktandem/tandem/issues/86 Populate backlog of new projects.

**Comment by serundeputy** [comment]
> 7. @labboy0276 any other steps we usually do that i've missed

I don't know if it something you missed, but a thing that it seems most/all of us agree to is spinning up a minimum backlog that should contain cards we know we need or are likely to need on every project.

Current cards I think we've identified:

* Migrations
  * Preferably with some way to QA them in parts or in whole
* Google Analytics
  * GA in specific and in general identifying the scope of SEO for the project (how important is it to the project, i.e. RMC is not very to Poets.org which is very very)
.
.
.

**Comment by pirog** [comment]
@serundeputy i'd say those are out of scope for this particular ticket, mostly because we don't know what those things are yet. 

That said, i think we've all flagged some sort of "auto backlog population" as something we want in the future so what i would recommend is for you to spin up a task to start moving in that direction. 

Presumably that task would be creating a list of tickets we'd like to see in all our projects. Then we can continue to flesh out those tickets, get them added to the templates section of our docs and the guide @labboy0276 is working on here, and then ultimately baked into a `lando-tandem` plugin for the automation win. 

You want to take a crack at spinning that ticket up?

**Comment by labboy0276** [comment]
I will get to this one next week @pirog

**Comment by labboy0276** [comment]
OK @pirog this is the first pass at said documents, it will be happier in markdown, but there isnt too much outside of this that we need to do anymore.  Our start states are in a good spot:

https://docs.google.com/document/d/1jJrs0cUK9gS_9TgtkxmX_I6tLylXeutUKdJyco2vMf4/edit

**Comment by pirog** [comment]
@labboy0276 ok this is a pretty good start. i've dropped some comments in the doc for you. do some edits and then lets try to get it up in the markdown

**Comment by labboy0276** [comment]
@pirog https://github.com/thinktandem/tandem/pull/120
