### ISSUE TITLE
Get Mike Fucking Milano on the webstie

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#82]
## What is to be done?

Are we ashamed of @mikemilano? If we arent (which we very much arent) then that BAMF should be up on the Tandem site with the rest of us!
https://thinktandem.io/about/

@mikemilano if you've got a good headshot i'd slack it to @labboy0276 so he can add it to the site. I'd also check out the [about page](https://thinktandem.io/about/) and hover over each person. You'll see a nice quoteblock show up for each person. This gives you a small opportunity to let people know how you roll. You also will want to tell @labboy0276 your position and competencies. This might be a good starting point

```yaml
name: Mike Milano
job: Senior Architect
skills: Drupal, Symfony and Echolocation
quote: the power of a thousand suns
```

Usually i'd take this opportunity to get you deving on our website @mikemilano but its pretty spaghetti right now and im guessing by extension A TRAP! so let's just have @labboy0276 hook it up.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

**Comment by mikemilano** [comment]
I am to blame. @labboy0276 asked me for a photo and all I failed to deliver.

Also, I'm somewhat politically closeted based on the extreme left leaning tendencies of our industry. Happy to share with people I know that can think critically, and for themselves, but unfortunately the far left collective mind like to label even left-leaning centrists as evil or alt-right.

Here's a picture: 
![mike-drupal](https://user-images.githubusercontent.com/1287855/62167883-0733e680-b2d9-11e9-97c8-62d3d51c72f2.jpg)

**Comment by labboy0276** [comment]
He is on there @pirog https://thinktandem.io/about/

**Comment by pirog** [comment]
yes he is!
