### ISSUE TITLE
Move over old project roles in new PM guides

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#89]
## What is to be done?

We've got these old project roles
https://docs.v1.thinktandem.io/project-management/roles-responsibilities.html#roles--responsibilities

We probably want ot move them into our PM GUIDES
https://tandem-docs.lndo.site/guides/

@dustinleblanc in the process of doing this if you see any "issues" with the current set of roles and responsibilities feel free to either update/edit them if you are feeling confident those edits better reflect our current situation or open up relevant discussions about proposed changes if you feel that is better. use your discretion and spidey sense and SCOPE SHIT WELL! 

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

**Comment by dustinleblanc** [comment]
PR #92 is up for this. I don't think we need much further discussion about these roles for now.
