### ISSUE TITLE
[lando-tandem plugin] Determine initial feature set for an MVP.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#93]
## What is to be done?

What is the minimum feature set we are after for the `lando-tandem` MVP?

* `lando create-project` command
  * create gitub repo/zen board from a chosen start state
  * populate backlog w/ known cards we need on every project
  * create Tandem GH labels
*
*
*

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

* GH Labels issue https://github.com/thinktandem/tandem/issues/94
* GH Backlog of cross project common issues https://github.com/thinktandem/tandem/issues/95
* Make sure our DevOps are winning https://github.com/thinktandem/tandem/issues/97
* Update mechanisn https://github.com/thinktandem/tandem/issues/98

**Comment by pirog** [comment]
@serundeputy ill take a crack at this early next week

**Comment by pirog** [comment]
So this needs more work, but i think generally we are looking to automate this flow as soon as possible
https://docs.google.com/document/d/1jJrs0cUK9gS_9TgtkxmX_I6tLylXeutUKdJyco2vMf4/edit

This means our MVP does basically two things: 

1. Spins up new projects from start states
2. Pulls down extant projects 

### New projects

1. `lando new-project`, auth with a user/name pass,
2. get a list of start states, choose start state
3. put in basic shit like project name, etc
4. get an option to set up the project on p.sh with github integration

### Extant projects

1. lando init --source tandem
2. auth with user/pass
3. get list of projects
4. choose project, 
5. "clones" project down from p.sh like that pantheon integration does

@serundeputy i think this sets the "base" for our plugin and we can then add in automatic issue queue population etc. what do you think? am i missing anything huge?

**Comment by pirog** [comment]
@mikemilano this is pretty high level but should give you an idea about at least some of the immediate things wed need from the tandem hub

**Comment by pirog** [comment]
@mikemilano @serundeputy i dropped a slightly more fleshed out version of the MVP over at 
https://github.com/thinktandem/lando-tandem#roadmap
it still needs some clarification but should be good enough for us to begin
