### ISSUE TITLE
[lando-tandem plugin] Create a list of Tandem GH issue Labels.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#94]
## What is to be done?

We need a list of GH labels that we will use on all projects. We will decide on that list here in this issue.

Labels:
* bug
* feature
* blocked
* needs clarification
*
*
*

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Once we have a list let's update #93 to have this list included in the feature set spec for `lando-tandem` MVP.

**Comment by labboy0276** [comment]
question is a good one to use as well
