### ISSUE TITLE
[lando-tandem plugin] Create a list GH Backlog issues.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#95]
## What is to be done?

We need to capture backlog issues that should be in every Tandem project so that we don't miss important things in projects.

Issues for backlog:
* Migrations
  * Migrations QA criteria
* SEO
  * Google Analytics
* DevOps
  * Launch card
*
*
*

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

Once we decide on the canonical issues list let's update #93 with the info for the MVP spec.

**Comment by dustinleblanc** [comment]
@labboy0276 I got started on a high-level list here: https://github.com/thinktandem/tandem/commit/fb404be9c24db15cafec7c1a61f2722528fb6dd9

**Comment by labboy0276** [comment]
@dustinleblanc this is a pretty good list.  I would remove these two:

```
Perform SEO audit on existing site if any
Perform performance audit on existing site if any
```

And just put something like

```
Perform audits on current site (migration, seo, performance, etc) according to SOW.
```

I have some notes from poets and what I will win on twinstar here: https://docs.google.com/document/d/1HpYcq2_nbww-pU80xII3_j2isEJqZJnX5g8H2Ww29JE/edit

So we will need to write out cards for those as well pre and post.  As a FYI, The url checker module is on poets and I need to create a repo for it.
