### ISSUE TITLE
[lando-tandem plugin] We need an update mechanism for lando-tandem.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/tandem#98]
## What is to be done?

Need to write an update mechanism/script that will live as part of the `lando-tandem` plugin.

* make it simple for Tandemites to keep up with the latest feature sets of `lando-tandem`
* users should be able to type `lando lando-tandem-update` to get the latest and greatest code and feature sets

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task
- [x] I've also gone into any applicable follow up tasks and [set this issue as a dependency](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)

## Next steps(s)

I think this is a one off task, but we can add follow ups here if they arise.

**Comment by pirog** [comment]
@serundeputy awesome. Did you have a technical implementation in mind for this yet? Would love to hear some ideas before we start to make moves

**Comment by pirog** [comment]
@serundeputy i did some research on this and wanted to report some findings that i think lock down our architecture a bit more.

1. Lando `node` services _do_ include `git` as well as `node`, `yarn` and `npm`
2. `yarn add` _does_ let you pull from basically any `git` hash, tag, branch but it _does not_ leave you with a functioning git repo

For these reasons i think we want to have the following architecture

1. This plugin should be updated by invoking lando eg `lando update-tandem` (or whatever)
2. `lando update-tandem` should take options that it passes into a bash script that we mount inside a `node` LTS service eg very similar to how we do `lando pull` 
3. This means that updates are happening inside a node service
4. Script should check to see if the plugin was installed via git (eg has a .git directory) and if so then it should try to git pull origin master, this handles the case of someone has manually cloned the plugin so they can dev it (which presumably will be most of us for the foreseeable future)
5. If was not installed by git we can fall back to https://yarnpkg.com/lang/en/docs/cli/upgrade/ and then maybe the npm variant and then an error. I'm guessing pulling the latest makes the most sense for now.

Longer term (probably want to create a cards for these as needed) we can add options to the update script so the user can upgrade to specific versions. We also will eventually want to get this functionality generic and added directly into lando eg `lando plugin update PLUGINNAME`
